### ISSUE TITLE
error during payout

### ISSUE THREAD

**Issue by ligi** [gitcoinco/grants-round#1054]
**Overview**

I had a problem contributing on the alpha round. I started the payment process - but then aborted in order to switch to gashawk - then I was in a loop with this:

![image](https://user-images.githubusercontent.com/111600/215013448-b965d390-24d3-409f-9111-654c4d61a40a.png)

pressing try again and got this error again

This is in the logs:
```
instrument.ts:124 Error while bulk submitting donations:  Error: sending a transaction requires a signer (operation="sendTransaction", code=UNSUPPORTED_OPERATION, version=contracts/5.6.0)
    at f.makeError (index.ts:261:28)
    at f.throwError (index.ts:273:20)
    at P.<anonymous> (index.ts:420:20)
    at Generator.next (<anonymous>)
    at strings.ts:2:28
    at new Promise (<anonymous>)
    at h (strings.ts:2:28)
    at P.<anonymous> (index.ts:418:46)
    at application.ts:64:41
    at QFDonationContext.tsx:216:11
    at Zz (QFDonationContext.tsx:140:11)
    at submitDonations (QFDonationContext.tsx:176:12)
    at Ce (ViewBallotPage.tsx:1149:13)
    at onClick (ErrorModal.tsx:100:25)
    at Object.Te (react-dom.production.min.js:54:317)
    at Ue (react-dom.production.min.js:54:471)
    at react-dom.production.min.js:55:35
    at zr (react-dom.production.min.js:105:68)
    at Lr (react-dom.production.min.js:106:380)
    at react-dom.production.min.js:117:104
    at lc (react-dom.production.min.js:273:42)
    at Oe (react-dom.production.min.js:52:375)
    at Jr (react-dom.production.min.js:109:469)
    at Zt (react-dom.production.min.js:74:59)
    at Wt (react-dom.production.min.js:73:73)
    at HTMLDivElement.r (helpers.ts:98:1)
```

**Steps To Reproduce**
1. Go to 'Donation Builder'
2. Click on 'Submit your donation'
3. Abort in MetaMask
4. Switch network to gashawk
5. be in the "try again loop"

---

also the wallet is logged out then - when I reconnect the wallet everything is working again - so I guess this is the root problem - when "try again" it should check if a wallet is connected - if not call "connect wallet"

**Comment by ligi** [comment]
Another problem in the context of gashawk is: 
with gashawk it can take long until the tx confirms (by design to save gas fees) - if you loose the window in the meantime you seem to need to start over. Would be good if the payout could check in the flow if there is an approval with the amount already and skips this step then.

**Comment by vacekj** [comment]
Closing as stale, please raise an issue in Intercom if this ever comes up again.
